project/friendbook/friendbook/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'bookmarks.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^friendbook/', include('main.urls'))
)

project/friendbook/main/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from main import views
from django.contrib import admin
admin.autodiscover()


'''
The first 11 URIs are for viewing the website while the after 9th URI and on are
for the RESTful API.  For more information on this RESTful service, please read
the methods associated with them in views.py.
'''
urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^server_admin/$', views.server_admin, name='server_admin'),
    url(r'^newpost/$', views.newpost, name='newpost'),
    url(r'^friendship/$', views.friendship, name='friendship'),
    url(r'^friendship_accept/$', views.friendship_accept, name='friendship_accept'),
    url(r'^unfriend/$', views.unfriend, name='unfriend'),
    url(r'^search_users/$', views.search_users, name='search_users'),
    url(r'^authors$', views.users, name='users'),
    url(r'^author/$', views.users, name='users'),
    url(r'^wall/$', views.wall, name='wall'),
    url(r'^account/$', views.account, name='account'),
    url(r'^author/posts/$', views.posts, name='posts'),
    url(r'^author/(?P<userID>[\w\-]+)$', views.user, name='user'),
    url(r'^author/(?P<guid>[\w\-]+)/activate/$', views.activate_user, name='activate_user'),
    url(r'^author/(?P<guid>[\w\-]+)/modify/$', views.modify_user, name='modify_user'),
    url(r'^author/(?P<guid>[\w\-]+)/delete/$', views.delete_user, name='delete_user'),
    url(r'^posts/$', views.pubposts, name='pubposts'),
    url(r'^author/(?P<user_id>[\w\-]+)/posts/$', views.authorposts, name='authorposts'),
    url(r'^posts/(?P<post_id>[\w\-]+)/$', views.post, name='post'),
    url(r'^author/(?P<userID>[\w\-]+)/posts/(?P<post_id>[\w\-]+)/comments/$', views.comments, name='post'),
    url(r'^author/(?P<username>\w+)/posts/(?P<post_id>[\w\-]+)/comments/$', views.comments, name='post'),
    url(r'^author/(?P<username>\w+)/friends/$', views.friends, name='friends'),
    url(r'^author/(?P<username>\w+)/friends/(?P<friend_id>\w+)/$', views.friend, name='friend'),
    url(r'^author/(?P<username>\w+)/images/$', views.images, name='images'),
    url(r'^friendrequest/$', views.friendrequest, name='friendrequest'),
    url(r'^friends/(?P<username>[\w\-]+)/$', views.friends, name='friends'),
    url(r'^friends/(?P<username>[\w\-]+)/(?P<friend_id>[\w\-]+)/$', views.friend, name='friend'),

    url(r'^images/$', views.images, name='images'),
    url(r'^admin/', views.server_admin, name='server_admin')


)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/friendbook/main/models.py
from django.db import models
from django.forms import ModelForm
from django import forms

PERMISSION_LEVELS = (
    ("PUBLIC"    ,"public"),
    ("FOAF"      , "friends of all friends"),
    ("FRIENDS"   , "friends"),
    ("PRIVATE"   , "private"),
    ("SERVERONLY", "server only"),
)

class Users(models.Model):
    guid = models.CharField(max_length=100, primary_key=True)
    username = models.TextField(unique=True)
    password = models.TextField()
    role = models.TextField()
    register_date = models.DateTimeField(auto_now_add=True, blank=True)
    active = models.BooleanField()
    github_account = models.TextField(blank=True)

class Posts(models.Model):
    guid = models.CharField(max_length=100, primary_key=True)
    title = models.CharField(max_length=30)
    source = models.URLField(blank=True)
    origin = models.URLField(blank=True)
    description = models.CharField(max_length=100, blank=True)
    category = models.CharField(max_length=100, blank=True)
    content_type = models.CharField(max_length=30)
    content = models.TextField()
    author   = models.ForeignKey(Users)
    permission = models.CharField(max_length=100,choices=PERMISSION_LEVELS)
    pubdate = models.DateTimeField(auto_now_add=True, blank=True)

class Comment(models.Model):
    guid = models.CharField(max_length=100,primary_key=True)
    postguid = models.ForeignKey(Posts)
    author = models.ForeignKey(Users)
    comment = models.TextField()
    pubDate = models.DateTimeField(auto_now_add=True, blank=True)

class ServerPermission(models.Model):
    permission = models.TextField()
    value = models.BooleanField()

class Friends(models.Model):
    username1 = models.TextField()
    username2 = models.TextField()
    accept = models.BooleanField()
    server = models.TextField(blank=True)

class Image(models.Model):
    user = models.ForeignKey(Users)
    name = models.CharField(max_length=30)
    image = models.ImageField(upload_to='images')

class ImageForm(ModelForm):
    class Meta:
        model = Image
        exclude = {'user',}

class UserForm(ModelForm):
    class Meta:
        model = Users
        exclude = {'guid','password','active'}
        widgets = {
            'username': forms.TextInput(attrs={'class':'form-control'}),
            'role': forms.TextInput(attrs={'class':'form-control'}),
            'github_account': forms.TextInput(attrs={'class':'form-control'}),
        }

class PostsForm(ModelForm):
    class Meta:
        model = Posts
        fields = ['title','category','description','content','permission']
        exclude = ("author",)

    def __init__(self, *args, **kwargs):
        super(PostsForm, self).__init__(*args, **kwargs)
        self.fields['permission'].widget.attrs.update({'class':'col-sm-9 form-control','style':"width: 90%;"})
        self.fields['title'].widget.attrs.update({'style':"width: 90%;",'placeholder':"Please input the author's username."})
        self.fields['category'].widget.attrs.update({'style':"width: 90%;",'placeholder':"(e.g. Medical, Health)"})
        self.fields['description'].widget.attrs.update({'style':"width: 90%;",'placeholder':"Description of the post"})

class ServerPermissionForm(ModelForm):
    class Meta:
        model = ServerPermission
        fields = ['value']

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']
        exclude = ("postguid",)
        def __init__(self, *args, **kwargs):
            super(PostsForm, self).__init__(*args, **kwargs)
            self.fields['coment'].widget.attrs.update({'style':"width: 90%;"})
        

project/friendbook/main/forms.py
from django import forms

project/friendbook/main/views.py
from django.shortcuts import render
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.shortcuts import redirect
from django.http import HttpResponse,StreamingHttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.views.decorators.http import require_http_methods
from django.views.decorators.csrf import csrf_exempt
from django.core.serializers.json import DjangoJSONEncoder
from django.core import serializers
from django.db import IntegrityError
from django.db.models import Q
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from main.models import Users, Posts, Comment , Friends, ServerPermission, PostsForm, CommentForm, Image, ImageForm, UserForm, ServerPermissionForm
from django.core.urlresolvers import reverse
from django.contrib.admin.views.decorators import staff_member_required
from django.core.exceptions import PermissionDenied

import json
import time
from datetime import datetime
import urllib
import urllib2
import uuid
import urlparse

@require_http_methods(["GET", "POST"])
def index(request):
    context = RequestContext(request)
    if (request.method == "GET"):
        logout(request)
        return render_to_response('main/index.html', context)
    else:
        if ("login" in request.POST):
            username = request.POST["username"]
            password = request.POST["password"]
            
            if (len(Users.objects.filter(username = username, password = password)) == 1):
                if ((Users.objects.get(username = username, password = password)).active == 1):
                  request.session["loggedIn"] = True
                  request.session["username"] = username
                  request.session["guid"] = Users.objects.get(username = username).guid
                
                  return redirect("wall")
                else:
                  return render_to_response("main/index.html", {"loginError": "Error: you haven't been verified by the website admin yet"}, context)
            else:
                return render_to_response("main/index.html", {"loginError": "Error: wrong username/password"}, context)
        else:
            guid = uuid.uuid4()
            username = request.POST["username"]
            password = request.POST["password"]
            role = "Author"
            registerDate = datetime.now().date()
            active = 0
            github = request.POST["github"]
            
            try:
                newUser = Users(guid = guid, username=username, password=password, role=role, register_date=registerDate, active=active, github_account=github)
                newUser.save()
            except IntegrityError as e:
                return render_to_response('main/index.html', {"signupError": "Error: username already exists"}, context)
            
            return render_to_response('main/index.html', {"signupSuccess": "Successfully created an account! Before you can login, the website admin has to verify who you are"}, context)

@require_http_methods(["GET", "POST"])
def account(request):
  context = RequestContext(request)
  guid = request.session["guid"]
  message = ""
  error = ""

  if (request.method == "POST"):
    if (len(Users.objects.exclude(guid = guid).filter(username = request.POST["username"])) == 0):
      Users.objects.filter(guid = guid).update(username = request.POST["username"], password = request.POST["password"], github_account = request.POST["github"])
      message = "Account successfully updated"
    else:
      error = "Username already exists"

  user = Users.objects.get(guid = guid)
  return render_to_response("main/account.html", {"username": user.username, "password": user.password, "github": user.github_account, "message": message, "error": error}, context)

@require_http_methods(["GET"])
def logout(request):
  context = RequestContext(request)

  request.session["loggedIn"] = False
  request.session["username"] = ""
  request.session["guid"] = ""

  return redirect("index")
  

@staff_member_required
def server_admin(request):
    context = RequestContext(request)

    article_posts = get_server_permission('can_share_posts')
    article_images = get_server_permission('can_share_images')

    if request.method == 'POST':

        share_posts = request.POST.get('public_posts')
        share_images = request.POST.get('public_images')

        article_posts.value = True if share_posts else False   
        article_posts.save() 
        article_images.value = True if share_images else False
        article_images.save() 

    context['users'] = list(Users.objects.all())
    context['share_posts'] = article_posts.value
    context['share_images'] = article_images.value
    return render_to_response('main/server_admin.html', context)

def users(request):
  if request.method == 'GET':
    response_data = serializers.serialize('json', Users.objects.all())
    return HttpResponse(response_data)
  else:
    return HttpResponseNotAllowed

def getGitHubEvents(githubAccount):
    if githubAccount:
        response = urllib2.urlopen("https://api.github.com/users/"+githubAccount+"/events").read()
        jsonResponse = json.loads(response)
        for item in jsonResponse:
            item["pubDate"] = item["created_at"]
            del item["created_at"]
            stripedDate = item["pubDate"].replace('Z', '')
            stripedDate = stripedDate.replace('T', ' ')
            postDate = datetime.strptime(stripedDate, '%Y-%m-%d %H:%M:%S').strftime('%b %d, %Y at %H:%M')
            item["pubDate"] = postDate
        return jsonResponse
    else:
        return list()

'''
This method is triggered by URI http://127.0.0.1:8000/wall/
to display the post wall.  The GET method just gets all posts that the
user has access to and sends it back to the postwall.html for display.

The POST method can be for two purposes: for creating new post or for
editting an existing post.  In both cases the data is taken from the POST
body and inserted into the main_posts database table.
'''
@csrf_exempt
@require_http_methods(["GET", "POST"])
def wall(request):
    context = RequestContext(request)
    currentHost = request.get_host()
    me = request.session["username"]
    userInfo = Users.objects.get(username=me)
    if request.method == "POST":
        f = PostsForm(request.POST,request.FILES)
        if f.is_valid():
            new_post = f.save(commit=False)
            new_post.author = userInfo
            new_post.source = currentHost
            new_post.origin = currentHost
            #need the db guid field to be string
            new_post.guid = uuid.uuid4()
            new_post.save()
        else:
            print "invalid form"
    #GET request
    githubActivity = getGitHubEvents(userInfo.github_account)
    authorposts = Posts.objects.filter(author=userInfo)
    publicPosts = Posts.objects.filter(permission="PUBLIC").exclude(author=userInfo)
    
    friends = list(Friends.objects.all())
    friend_check = [x.username2 for x in friends if (x.username1 == me and x.accept== 1)] + [x.username1 for x in friends if (x.username2== me and x.accept== 1)]
    
    friend_infos = []
    for friend in friend_check:
        friendDict = dict()
        try:
            friendUser = Users.objects.get(username=friend)
            friendDict["username"] = friend
            friendDict["guid"] = friendUser.guid
            friend_infos.append(friendDict)
        except:
            print friend

    authorData = post2Json(currentHost, authorposts).get("posts")
    publicPosts = post2Json(currentHost, publicPosts).get("posts")
    serverOnlyPosts = getServerOnlyPosts(me, currentHost, friend_check)
    friendsPosts = getAllFriendPosts(me, currentHost, friend_check)
    
    mergedList = githubActivity + authorData + publicPosts + serverOnlyPosts + friendsPosts
    mergedList.sort(key = lambda item:datetime.strptime((item["pubDate"]), '%b %d, %Y at %H:%M'), reverse = True)

    return render_to_response('main/postwall.html', {"user_id": userInfo.guid, "username": request.session['username'], "posts": mergedList, "comment_form":CommentForm(), "friends": friend_infos}, context)

'''
    This method gets all the posts made by the currently authenticated
    user's friends by querying the database.
    
    @param  user        currently authenticated user
    @param  host        current host
    @param  friendlist  username list of friends
    @return             list of all posts
'''
def getAllFriendPosts(user, host, friendlist):
    postList = []
    for friend in friendlist:
        friendInfo = Users.objects.get(username=friend)
        friendServer = Friends.objects.filter(Q(username1=friend, username2=user)|Q(username2=friend, username1=user)).values("server")
        friendPosts = Posts.objects.filter(permission="FRIENDS", author=friendInfo)
        
        if friendServer[0].get("server"):
            friendPosts = post2Json(friendServer[0].get("server"), friendPosts).get("posts")
            postList += friendPosts
        else:
            friendPosts = post2Json(str(host), friendPosts).get("posts")
            postList += friendPosts
    return postList

'''
    This method gets all the posts made by the currently authenticated
    user's friends within the same server by querying the database.
    
    @param  user        currently authenticated user
    @param  host        current host
    @param  friendlist  username list of friends
    @return             list of all posts
'''
def getServerOnlyPosts(user, host, friendlist):
    postList = []
    for friend in friendlist:
        friendInfo = Users.objects.get(username=friend)
        friendServer = Friends.objects.filter(Q(username1=friend, username2=user)|Q(username2=friend, username1=user)).values("server")
        friendPosts = Posts.objects.filter(permission="SERVERONLY", author=friendInfo)
        
        if friendServer[0].get("server") == "":

project/friendbook/templates/main/account.html
{% load static  %}
<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <title>Account Management</title>
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"/>
        <link href="{% static 'css/blog.css'%}" rel="stylesheet"/>
        <script type="text/javascript" src="{% static 'js/jquery/jquery-1.8.3.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/tinymce/tinymce.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/postwall.js' %}"></script>
    </head>
    <body>
        <div class="navbar-wrapper">
            <div class="container">
                <div class="navbar navbar-inverse navbar-static-top" role="navigation">
                    <div class="container">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <a class="navbar-brand">Friendbook</a>
                        </div>
                        <div class="navbar-collapse collapse">
                            <ul class="nav navbar-nav">
                                <li><a href="{% url 'wall' %}">Post Wall</a></li>
                                <li><a href="{% url 'newpost' %}">Create Post</a></li>
                                <li><a href="{% url 'search_users' %}">Search Users</a></li>
                                <li class="active"><a href="#">Account Management</a></li>
                                <li><a href="{% url 'logout' %}">Logout</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="well">
                    <h3>Account Management</h3>
                    <form class="form-horizontal" action="{% url 'account' %}" method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="username" class="col-sm-3">Username<span class="text-danger">*</span></label>
                            <div class="col-sm-9">
                                <input type="text" name="username" id="username" value="{{ username }}">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="password" class="col-sm-3">Password<span class="text-danger">*</span></label>
                            <div class="col-sm-9">
                                <input type="password" name="password" id="password" value="{{ password }}" required>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="github" class="col-sm-3">Github Account</label>
                            <div class="col-sm-9">
                                <input type="text" name="github" id="github" value="{{ github }}">
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <div class="col-sm-9">
                                <button class="btn btn-primary btn-md" type="submit">Update Account</button>
                            </div>
                        </div>

                        <div class="form-group">
                            {% if error != "" %}
                                <p class="text-danger">{{ error }}</p>
                            {% else %}{% if message != "" %}
                                <p class="text-success">{{ message }}</p>
                            {% endif %}{% endif %}
                        </div>
                    </form>
                </div>
            </hr>
        </div>
    </div>

    </body>
</html>

project/friendbook/templates/main/create_post.html
{% load static  %}
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <title>Friendbook</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/blog.css'%}" rel="stylesheet"/>
    <link href="{% static 'css/bootstrap-markdown.min.css'%}" rel="stylesheet"/>
    <script type="text/javascript" src="{% static 'js/jquery/jquery-1.8.3.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/to-markdown.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/markdown.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap-markdown.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/tinymce/tinymce.min.js' %}"></script>
    <script type="text/javascript">
    $(document).ready(function() {
        var currentEditor = "tinymce";
        $('#markdown_content').hide();
        $("#spec_author_div").hide();
        $("#post_permissions").change(function() {
            var currentVal = $(this).val();
            if(currentVal == "spec_autor")
            {
                $("#spec_author_div").show();
            }
            else
            {
                $("#spec_author_div").hide();
            }
        });
        tinymce.init({
         mode: 'exact',
         elements:"id_content",
         width: '90%',
         plugins: [
         "advlist autolink lists link image charmap preview anchor",
         "searchreplace visualblocks code fullscreen",
         "insertdatetime media table contextmenu paste"
         ],
         toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
        });
        $('#switch_editor').click(function(){
            if(currentEditor == "tinymce"){
                $('#tinymce_content').hide();
                $('#markdown_content').show();
                $('#markdown_textarea').attr('name','content');
                $('#id_content').removeAttr('name');
                var text = tinymce.get('id_content').getContent()
                $('#markdown_textarea').val(toMarkdown(text));
                currentEditor = "markdown";
            }
            else if(currentEditor == "markdown"){
                $('#markdown_content').hide();
                $('#tinymce_content').show();
                $('#id_content').attr('name','content')
                $('#markdown_textarea').removeAttr('name');
                var text = $('#markdown_textarea').val();
                tinyMCE.activeEditor.setContent(markdown.toHTML(text));
                currentEditor = "tinymce";
            }
        });
        $("#new_post").submit(function( event ) {
            if(currentEditor == "markdown"){
                var text = $('#markdown_textarea').val();
                $('#markdown_textarea').val(markdown.toHTML(text));
            }
            return true;
        });
    });
    </script>
</head>


<body>
    <div class="navbar-wrapper">
        <div class="container">
            <div class="navbar navbar-inverse navbar-static-top" role="navigation">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="#">Friendbook</a>
                    </div>
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li><a href="{% url 'wall' %}">Post Wall</a></li>
                            <li class="active"><a href="#">Create Post</a></li>
                            <li><a href="{% url 'search_users' %}">Search Users</a></li>
                            <li><a href="{% url 'account' %}">Account Management</a></li>
                            <li><a href="{% url 'images' %}">View Images</a></li>
                            <li><a href="{% url 'logout' %}">Logout</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            
        </div>
    </div>


    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="well">
                    <h3>Create Post</h3>
                    <form id="new_post" class="form-horizontal" action="{% url 'wall' %}" method="POST">
                        <div class="form-group">
                            <label for="id_permission" class="col-sm-3">Permissions:</label>
                            <div class="col-sm-9">
                                {{ form.permission }}
                            </div>
                        </div>
                        <div id="spec_author_div" class="form-group">
                            <label for="spec_author_input" class="col-sm-3"> Author's username:</label>
                            <div class="col-sm-9">
                                <input id="spec_author_input" name="spec_author_input" style="width: 90%;" placeholder="Please input the author's username."/>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="post_title" class="col-sm-3">Title: </label>
                            <div class="col-sm-9">
                                {{form.title}}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="id_category" class="col-sm-3">Category of the Post: </label>
                            <div class="col-sm-9">
                                {{form.category}}
                                <!--input type="text" id="post_category" name="post_category" style="width: 90%;" placeholder="(e.g. Medical, Health)"/-->
                            </div>
                        </div>

                        <!--div class="form-group">
                            <label for="id_content_type" class="col-sm-3">Content Type: </label>
                            <div class="col-sm-9">
                                {{form.content_type}}
                            </div>
                        </div-->
                        <div class="form-group">
                            <label for="id_description" class="col-sm-3">Post Description:</label>
                            <div class="col-sm-9">
                                {{form.description}}
                            </div>
                        </div>
                        <div class="form-group" style="padding-bottom:0px;margin-bottom:0px;">
                            <div class="col-sm-9">
                            </div>
                            <div class="col-sm-3" style="padding-left:77px;padding-bottom:0px;margin-bottom:0px;">
                            <input id="switch_editor" class="btn btn-primary btn-md" type="button" value="Switch Editor"/>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="id_content" class="col-sm-3">Post Content:</label>
                            <div id="tinymce_content" class="col-sm-9">
                                {{form.content}}
                            </div>
                            <div id="markdown_content" data-provide="markdown" rows="10" class="col-sm-9">
                                <div style="width:90%">
                                 <textarea id="markdown_textarea" data-provide="markdown" rows="13" style="line-height:20px;"></textarea>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3"></label>
                            <div class="col-sm-7">
                            <button class="btn btn-primary btn-md" type="submit">Post</button>
                            </div>
                        </div>
                    </form>
                </div><!-- /.well -->
            </hr>
        </div><!-- /.row -->
    </div>
</div><!-- /.container -->

</body>
</html>

project/friendbook/templates/main/layout.html
<!DOCTYPE html>

<html>
    <head>
        {% block head %}{% endblock %}
    </head>

    <body>
        {% block body %}{% endblock %}
    </body>
</html>